### ISSUE TITLE
Suggestion to link environment.yml in the installation instructions

### ISSUE THREAD

**Issue by darioflute** [SOFIA-USRA/sofia_redux#1]
Hi,
in the instructions to install the pipeline there is a suggestion to create an environment before installing the pipeline.
It would be nice to link the file, so that it would be possible to download it from the page instead of going back to the 
list of files.
Cheers,
Dario

**Comment by melanieclarke** [comment]
Good idea - thanks, Dario.  I'll get that change in.

**Comment by melanieclarke** [comment]
Done, and updated in the posted docs.
