### ISSUE TITLE
Add direct link to raw environment file

### ISSUE THREAD

**Issue by darioflute** [SOFIA-USRA/sofia_redux#2]
Hi,
I noticed that a link has been added in the instructions for the installation of the pipeline.
It can happen (it happened to me) that the user downloads directly the file from the link.
It will have a file in html and this will fail to create a new environment.
I suggest to directly link the raw file:
https://raw.githubusercontent.com/SOFIA-USRA/sofia_redux/main/environment.yml

Cheers,
Dario

**Comment by melanieclarke** [comment]
Done!  Let me know if that works better for you.

**Comment by darioflute** [comment]
It works perfectly !
Thanks,
Dario
